### ISSUE TITLE
error oauth_listener() 

### ISSUE THREAD

**Issue by mryap** [michalbrys/R#1]
I am getting the error oauth_listener() needs an interactive environment and then it halts execution when running this part of the script.

> token <- Auth(client.id,client.secret)
> save(token,file="./token_file")
> ValidateToken(token)

 Did Google update its API and render this code unworkable? 

 Thanks

**Comment by michalbrys** [comment]
Just updated R code to use another library.
You can find more examples here: [https://github.com/michalbrys/R-Google-Analytics](https://github.com/michalbrys/R-Google-Analytics)
